version: "3.8"

services:
  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    restart: unless-stopped

    volumes:
      - /var/log/nginx:/var/log/nginx:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro

    command:
      - -config.file=/etc/promtail/config.yml